### ISSUE TITLE
Prop Anarchy support

### ISSUE THREAD

**Issue by taibenvenuti** [TPBCS/ForestBrush#41]
It has been reported that this doesnt work with anarchy.
Note to self: Just make the water collision check hotkey also work for all other types of collisions.

**Comment by taibenvenuti** [comment]
Fixed?
Needs verifying.

**Comment by Sipke82** [comment]
I often use this tool with size 1, so it places a random tree from my tree selection. Often i get the warning space occupied, while prop and tree anarchy is enabled. 
Same happens when using a larger size brush. However when i disable collision detection in the  fine road tool i think,  it works with large brushes, but still not working with brush size 1.
